### ISSUE TITLE
1.19.3 not supported

### ISSUE THREAD

**Issue by TwoPointInfinity** [fill1890/FabSit#18]
server crashes on load if server is on 1.19.3

**Comment by TwoPointInfinity** [comment]
[18:04:30] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabsit'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-launch.jar:0.11.1]
Caused by: java.lang.NoSuchFieldError: field_11145
	at net.fill1890.fabsit.entity.PoseManagerEntity.register(PoseManagerEntity.java:198) ~[fabsit-1.5.4+1.19.2.jar:?]
	at net.fill1890.fabsit.FabSit.<clinit>(FabSit.java:23) ~[fabsit-1.5.4+1.19.2.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.lang.Class.forName(Class.java:474) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	... 8 more

**Comment by TwoPointInfinity** [comment]
updated gradle.properties to this configuration but fails to build with 17 errors.

minecraft_version=1.19.3
yarn_mappings=1.19.3+build.5
loader_version=0.14.12

#Fabric api
fabric_version=0.72.0+1.19.3

build is fine on current 1.19.2 with https://scans.gradle.com/s/xsvtvtvcwd23m
